---
abstract: 'POD Object Model'
author:
  - 'Andy Wardley <abw@kfs.org>'
configure_requires:
  ExtUtils::MakeMaker: 6.48
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Pod::POM
name: Pod-POM
no_index:
  directory:
    - inc
    - t
requires:
  File::Slurp: 0
  Test::Differences: 0
  Test::More: 0
  Text::Wrap: 0
  YAML::Any: 0
version: 0.24
