---
abstract: 'POD Object Model'
author:
  - 'Andy Wardley <abw@kfs.org>'
build_requires:
  File::Slurp: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-POM
no_index:
  directory:
    - inc
    - t
requires:
  Text::Wrap: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.25
