--- #YAML:1.0
name:               Pod-POM
version:            0.22
abstract:           POD Object Model
author:
    - Andy Wardley <abw@kfs.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:    0
    File::Slurp:        0
    perl:               5.005
    Test::Differences:  0
    Test::More:         0
    Text::Wrap:         0
    YAML::Any:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
